apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"api-gateway","namespace":"petclinic"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":8080}],"selector":{"app":"api-gateway"},"type":"LoadBalancer"}}
  creationTimestamp: "2026-05-13T04:44:52Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  name: api-gateway
  namespace: petclinic
  resourceVersion: "77257"
  uid: c2f4f9b6-f656-4582-8eb5-dd296b763bc6
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.100.64.165
  clusterIPs:
  - 10.100.64.165
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30811
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-gateway
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: ac2f4f9b6f65645828eb5dd296b763bc-899362726.eu-west-1.elb.amazonaws.com
