apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"config-server","namespace":"petclinic"},"spec":{"ports":[{"port":8888,"protocol":"TCP","targetPort":8888}],"selector":{"app":"config-server"},"type":"ClusterIP"}}
  creationTimestamp: "2026-05-12T21:34:32Z"
  name: config-server
  namespace: petclinic
  resourceVersion: "4579"
  uid: 7e128ba9-9ed5-43a3-8ed8-d42252183915
spec:
  clusterIP: 10.100.129.252
  clusterIPs:
  - 10.100.129.252
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: config-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
