apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"customers-service","namespace":"petclinic"},"spec":{"ports":[{"port":8081,"protocol":"TCP","targetPort":8081}],"selector":{"app":"customers-service"},"type":"ClusterIP"}}
  creationTimestamp: "2026-05-12T21:45:37Z"
  name: customers-service
  namespace: petclinic
  resourceVersion: "6471"
  uid: b7502483-70bb-4e29-8ade-a637cd3a11eb
spec:
  clusterIP: 10.100.215.249
  clusterIPs:
  - 10.100.215.249
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: customers-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
