apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"discovery-server","namespace":"petclinic"},"spec":{"ports":[{"port":8761,"protocol":"TCP","targetPort":8761}],"selector":{"app":"discovery-server"},"type":"ClusterIP"}}
  creationTimestamp: "2026-05-12T21:40:13Z"
  name: discovery-server
  namespace: petclinic
  resourceVersion: "5548"
  uid: 3301dd10-11ad-4e6b-b190-646e94280290
spec:
  clusterIP: 10.100.120.68
  clusterIPs:
  - 10.100.120.68
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: discovery-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
