apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"vets-service","namespace":"petclinic"},"spec":{"ports":[{"port":8083,"protocol":"TCP","targetPort":8083}],"selector":{"app":"vets-service"},"type":"ClusterIP"}}
  creationTimestamp: "2026-05-13T04:33:30Z"
  name: vets-service
  namespace: petclinic
  resourceVersion: "75066"
  uid: b1041244-a207-41ad-8af6-34631cfa9ec2
spec:
  clusterIP: 10.100.7.109
  clusterIPs:
  - 10.100.7.109
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: vets-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
