apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"visits-service","namespace":"petclinic"},"spec":{"ports":[{"port":8084,"protocol":"TCP","targetPort":8084}],"selector":{"app":"visits-service"},"type":"ClusterIP"}}
  creationTimestamp: "2026-05-13T04:39:56Z"
  name: visits-service
  namespace: petclinic
  resourceVersion: "76279"
  uid: 854c8246-9d7d-4c91-9c4d-cb44f3c85527
spec:
  clusterIP: 10.100.25.117
  clusterIPs:
  - 10.100.25.117
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8084
    protocol: TCP
    targetPort: 8084
  selector:
    app: visits-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
