name: Java CI with Maven and Docker

on:
  push:
    branches:
      - main
      - feature/full-devops-deployment

  pull_request:
    branches:
      - main
      - feature/full-devops-deployment

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build project with Maven
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build customers-service Docker image
        run: |
          docker build -t klebervincent/customers-service:latest ./spring-petclinic-customers-service

      - name: Push customers-service Docker image
        run: |
          docker push klebervincent/customers-service:latest
