name: Spring Petclinic Full CI/CD

on:
  push:
    branches:
      - main
      - feature/full-devops-deployment

  pull_request:
    branches:
      - main
      - feature/full-devops-deployment

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build project with Maven
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Config Server
        run: |
          docker build -t klebervincent/config-server:latest ./spring-petclinic-config-server
          docker push klebervincent/config-server:latest

      - name: Build and Push Discovery Server
        run: |
          docker build -t klebervincent/discovery-server:latest ./spring-petclinic-discovery-server
          docker push klebervincent/discovery-server:latest

      - name: Build and Push Customers Service
        run: |
          docker build -t klebervincent/customers-service:latest ./spring-petclinic-customers-service
          docker push klebervincent/customers-service:latest

      - name: Build and Push Vets Service
        run: |
          docker build -t klebervincent/vets-service:latest ./spring-petclinic-vets-service
          docker push klebervincent/vets-service:latest

      - name: Build and Push Visits Service
        run: |
          docker build -t klebervincent/visits-service:latest ./spring-petclinic-visits-service
          docker push klebervincent/visits-service:latest

      - name: Build and Push API Gateway
        run: |
          docker build -t klebervincent/api-gateway:latest ./spring-petclinic-api-gateway
          docker push klebervincent/api-gateway:latest

      - name: Build and Push Admin Server
        run: |
          docker build -t klebervincent/admin-server:latest ./spring-petclinic-admin-server
          docker push klebervincent/admin-server:latest
